"""dropped name column

Revision ID: 47b20f440316
Revises: 4b8e7861a078
Create Date: 2021-11-29 08:02:50.410091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b20f440316'
down_revision = '4b8e7861a078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_column('fname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
