"""first commit migrations

Revision ID: 59627da2b688
Revises: 72c36dc807f0
Create Date: 2021-11-29 07:54:58.954040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59627da2b688'
down_revision = '72c36dc807f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_column('register', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('password', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('register', 'name')
    # ### end Alembic commands ###
